---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/website_54d8238e/core
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - cd $DEPLOYPATH && if [ -f .env ]; then test -f $HOME/composer.phar && php $HOME/composer.phar install --no-dev --optimize-autoloader --no-interaction --prefer-dist || true; fi
    - cd $DEPLOYPATH && if [ -f .env ]; then php artisan config:clear; php artisan view:clear; fi
    - cd $DEPLOYPATH && if [ -f .env ]; then php artisan migrate --force; fi
    - cd $DEPLOYPATH && if [ -f .env ]; then test -L public/storage || php artisan storage:link; fi
    - cd $DEPLOYPATH && if [ -f .env ]; then php artisan config:cache; php artisan route:cache; php artisan view:cache; fi
