<?php

namespace App\Providers;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Vite;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Blade::anonymousComponentPath(resource_path('views/layouts'), 'account');

        // Force HTTPS on all generated URLs in production (avoids "mixed content" errors).
        if ($this->app->environment('production')) {
            URL::forceScheme('https');
        }

        // Avoid the browser "preloaded but not used" warning: the stylesheet link already loads the CSS,
        // so the extra <link rel="preload" as="style"> generated by Vite is redundant with Livewire navigation.
        Vite::usePreloadTagAttributes(function (string $src, string $url, ?array $chunk, ?array $manifest) {
            return str_ends_with($url, '.css') ? false : [];
        });
    }
}
